# Step name
name: Build and Push Docker Image

# Trigger by push on main branch
on:
  push:
    branches:
      - main


# Run jobs
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          # more detail https://github.com/actions/checkout
          uses: actions/checkout@v4

        - name: Extract Docker image metadata
          id: meta
          # more detail https://github.com/docker/metadata-action
          uses: docker/metadata-action@v5
          with:
            images: ${{ secrets.DOCKER_USERNAME }}/basic-next

        - name: Log in to Docker Hub
          # more detail https://github.com/docker/login-action
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          # more detail https://github.com/docker/build-push-action
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/basic-next:latest
